version: '2'

services:

  gitlab_pipeline_annoyer:
    container_name: gitlab_pipeline_annoyer
    image: puzza007/gitlab_pipeline_annoyer
    restart: always
    ports:
      - "3000:3000"
    environment:
      - "TZ=Pacific/Auckland"
      - "RUST_LOG=info"
      - "SLACK_API_TOKEN=${SLACK_API_TOKEN}"
      - "SLACK_CHANNEL=${SLACK_CHANNEL}"
      - "GITLAB_API_HOSTNAME=${GITLAB_API_HOSTNAME}"
      - "GITLAB_API_TOKEN=${GITLAB_API_TOKEN}"
